### ISSUE TITLE
How to prevent all child elements? (nested)

### ISSUE THREAD

**Issue by NeoMarine** [phphe/vue-draggable-nested-tree#37]
I would like to be able to use create a list with maxLevel = 1. I noted that your solution in examples, is to use tree helper to set "droppable" to false, but this does not work as desired if maxLevel = 1, because then you cannot move nodes up/down your tree either, as nothing is "droppable"!

Even when I set :droppable="false" and :draggable="true", I still cannot move nodes up/down the tree.

DEMO: https://codepen.io/neomarine/pen/GwKqGW

**Comment by phphe** [comment]
it is a bug. I will try to fix it this weekend.

**Comment by NeoMarine** [comment]
Thank you. I have an idea for the fix. Perhaps have all the nodes within one parent node that has "droppable=true" (level 0) and then add starting nodes to that (which will be on level 1), that way you can reposition because node 0 will still be droppable.

**So you'll have e.g.**
- CONTAINER NODE (level 0) = droppable
-- My first node (level 1)
-- My second node (level 1)

**Comment by phphe** [comment]
latest 2.1.7 should solve that

**Comment by NeoMarine** [comment]
Hi phphe, I've found it does work but there is an issue still.

DEMO: https://codepen.io/neomarine/pen/GwKqGW

Try dragging any node up to the top of the list (e.g. move node 2,3 or 4 to node 1's position). It is difficult to do so. You need to drag "to the right" and up at the same time if you want to re-position at the top of the list.

**Comment by NeoMarine** [comment]
**Update**: I found my local copy wasn't working and I resolved the issue to being that I was not including the line: **cross-tree="cross-tree"**

With your latest update, it seems it is now _required_. If not, you cannot drag/re-position elements.

**Comment by NeoMarine** [comment]
Beautiful! Thank you for the fix!! Great work @phphe!

**Comment by NeoMarine** [comment]
Beautiful! Thank you for the fix!! Great work @phphe!

**Comment by NeoMarine** [comment]
@phphe unfortunately I've discovered a bug in this instance:
https://codepen.io/neomarine/pen/gQwMmR

Try dragging #2 (the only child element) and you will see some weird results.

**Comment by NeoMarine** [comment]
@phphe I'm unsure if it fixed it as it might be a result of another issue now: https://codepen.io/neomarine/pen/gQwMmR

_Cannot make a node become a child node._ It won't let you move a node to be a child node any longer. Currently, can only have 1 node level but in this example there SHOULD be 4 maximum.

**Comment by NeoMarine** [comment]
@phphe thank you for letting me know, it was a simple fix after all! So far lists are working wonderfully now. Great component you have here!
